name: demo_docker_compose

services:
 postgres:
   image: postgres:latest
   container_name: postgres_db
   environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin123
     POSTGRES_DB: my_database
   volumes:
     - postgres_data:/var/lib/postgresql/data
   ports:
     - "5432:5432"
   networks:
     - app_network

 pgadmin:
   image: dpage/pgadmin4:latest
   container_name: pgadmin
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@example.com
     PGADMIN_DEFAULT_PASSWORD: admin123
   ports:
     - "5050:80"
   networks:
     - app_network

volumes:
 postgres_data:
   driver: local

networks:
 app_network:
   driver: bridge
